PARSE_URL = "https://djinni.co/jobs/?primary_keyword=Python"

DOMAIN = "djinni.co"

TECHNOLOGIES = [
    "Python",
    "GCP",
    "CSS",
    "Jenkins",
    "React",
    "API",
    "GitLab CI",
    "SemVer",
    "Flask",
    "HTML",
    "OOP",
    "JWT",
    "JavaScript",
    "Kafka",
    "SQLAlchemy",
    "JSON",
    "Sphinx",
    "AWS",
    "Streamlit",
    "Django",
    "Bootstrap",
    "Azure",
    "Selenium",
    "Machine Learning",
    "Microservice",
    "Vue",
    "Git",
    "Linux",
    "WebSockets",
    "Graphql",
    "Kubernetes",
    "FastApi",
    "Pydantic",
    "Angular",
    "MongoDB",
    "DRF",
    "Algorithms",
    "MySQL",
    "Docker",
    "Asyncio",
    "PostgreSQL",
    "Pipenv",
    "REST Api",
    "Django Rest Framework",
    "Selenium",
    "Agile",
    "Scrapy",
    "Travis CI",
    "NoSQL",
    "HTML",
    "Nginx",
    "OAuth",
    "Loguru",
    "Jira",
    "PostgreSQL",
    "Microsoft Azure",
    "AI",
    "Celery",
    "Redis",
    "Vue",
    "NoSQL",
]
